### ISSUE TITLE
very slow responds when used as watchdog

### ISSUE THREAD

**Issue by kkmaslowski** [trombik/esphome-component-ping#13]
Hi. 
I'm trying to configure watchdog - if my TV responds to ping esp should enable relay with connected speakers and turn off when tv does not respond.
Problem is that if tv is turned on it takes about 1 minute to switch on relay, the same for turning off.

This is my configuration:

```
sensor:
  - platform: ping
    ip_address: 192.168.10.99
    num_attempts: 1
    timeout: 500ms
    loss:
      name: Packet loss
      id: loss
      on_value_range:
        - above: 99
          then:
          - switch.turn_off: relay
        - below: 1
          then:
          - switch.turn_on: relay
```

It seems that esp is 'blocked' between ping attempts for about 1minute.
