### ISSUE TITLE
loss sensor doesn't report value

### ISSUE THREAD

**Issue by Red5d** [trombik/esphome-component-ping#32]
I've configured my ping sensor like this:

    sensor:
      - platform: ping
        ip_address: 8.8.8.8
        num_attempts: 15
        timeout: 60sec
        loss:
          name: Packet Loss
          id: loss
          on_value:
          then:
            - switch.turn_off: relay
            - delay: 15s
            - switch.turn_on: relay

         update_interval: 30s

However, its state only shows up as "NA" in the esphome webui, or "Unknown" in Home Assistant. I've tested with it being able to reach 8.8.8.8 and also having a firewall rule that drops ICMP from its IP address, and the logs reflect that (ping success and failure), but the sensor value doesn't change at all. Am I missing something?

**Comment by trombik** [comment]
please provide logs.

**Comment by Red5d** [comment]
The only logs I get from it is this (repeated every minute) when ping is blocked:    

    19:20:24 | [I] | [ping:040] | no reply from 8.8.8.8

...and this when it's not blocked (every minute):

    21:06:24 | [I] | [ping:035] | 64 bytes from 8.8.8.8: icmp_seq=4 ttl=58 time=19 ms

Here's my full esphome config:

```
esphome:
  name: router-rebooter
  libraries:
    - ESP8266WiFi
    - https://github.com/akaJes/AsyncPing#95ac7e4

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

web_server:
  local: true

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Router-Rebooter Fallback Hotspot"

captive_portal:
    
external_components:
  - source:
      type: git
      url: https://github.com/trombik/esphome-component-ping
      ref: main

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Sonoff Basic Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "Sonoff Basic Relay"
    pin: GPIO12
    id: relay
    restore_mode: ALWAYS_ON

status_led:
  pin:
    number: GPIO13
    inverted: yes

sensor:
  - platform: ping
    ip_address: 8.8.8.8
    num_attempts: 15
    timeout: 60sec
    loss:
      name: Packet Loss
      id: loss
      on_value:
        then:
          - switch.turn_off: relay
          - delay: 15s
          - switch.turn_on: relay

    update_interval: 30s

```
