### ISSUE TITLE
multiple ping sensors

### ISSUE THREAD

**Issue by nagyrobi** [trombik/esphome-component-ping#36]
I see in the readme as known bug _multiple targets are not supported_. What does this exactly mean?

What I try to use is:

```
- platform: ping
  ip_address: 8.8.4.4
  update_interval: 120s
  num_attempts: 6
  timeout: 1sec
  latency:
    name: WAN Latency
    icon: mdi:console-network-outline
    accuracy_decimals: 3
  loss:
    id: loss_wan
    icon: mdi:console-network-outline
    name: WAN Packet loss
- platform: ping
  ip_address: 192.168.1.1
  update_interval: 120s
  num_attempts: 2
  timeout: 1sec
  loss:
    id: loss_gw
    icon: mdi:console-network-outline
    name: GW Packet loss
```

So one sensor is for `8.8.4.4`, the other one is for `192.168.1.1`. Is this supported or not?
I experienced reboots of the ESP32 (with Ethernet) every 1-2 hours...
