### ISSUE TITLE
Cannot compile on homeassistant

### ISSUE THREAD

**Issue by deanfourie1** [trombik/esphome-component-ping#38]
Hi I am attempting to compile this on esphome on homeassistant, but am facing the following error:

```
INFO ESPHome 2024.3.1
INFO Reading configuration /config/esphome/playbulb-candle.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing playbulb-candle (board: esp01_1m; framework: arduino; platform: platformio/espressif8266@3.2.0)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 1MB Flash
Dependency Graph
|-- ESPAsyncTCP-esphome @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 3.1.0
|-- DNSServer @ 1.1.1
|-- ESP8266WiFi @ 1.0
|-- ESP8266mDNS @ 1.2
|-- noise-c @ 0.1.4
|-- NeoPixelBus @ 2.7.3
Compiling .pioenvs/playbulb-candle/src/main.cpp.o
In file included from src/main.cpp:45:
src/ping_esp8266.h:22:10: fatal error: esphome/components/sensor/sensor.h: No such file or directory
   22 | #include "esphome/components/sensor/sensor.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
*** [.pioenvs/playbulb-candle/src/main.cpp.o] Error 1
```
========================== [FAILED] Took 1.44 seconds ==========================

I have included the libraries below:

```
esphome:
  name: playbulb-candle
  friendly_name: playbulb-candle
  includes:
    - ping/ping_esp8266.h          #file located here: /config/Keypad_I2C.h
    - asyncping/AsyncPing.h

esp8266:
  board: esp01_1m

# Enable logging
logger:
```

Any ideas what I am doing wrong here?
Thanks
